# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20171228_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('pYTHON\u6280\u672f', 'Python\u6280\u672f'), ('\u7ecf\u6d4e\u5b66\u6280\u672f', '\u7ecf\u6d4e\u5b66\u6280\u672f'), ('\u6570\u636e\u5e93\u6280\u672f', '\u6570\u636e\u5e93\u6280\u672f'), ('\u4e2a\u4eba\u5fc3\u60c5', '\u4e2a\u4eba\u5fc3\u60c5'), ('\u5176\u4ed6', '\u5176\u4ed6')], default=('pYTHON\u6280\u672f', 'Python\u6280\u672f'), max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='user_name',
            field=models.CharField(default='\u533f\u540d', max_length=20),
        ),
    ]
